import jsPDF from 'jspdf';

/**
 * Generates a balance statement PDF.
 * @param {object} wallet - The wallet object with balance info and transactions.
 * @param {Array} transactionsToExport - The array of transactions to include in the PDF.
 * @param {object} [filters] - Optional applied filters to display on the PDF.
 */
export const generateBalanceStatementPDF = async (wallet, transactionsToExport, filters = {}) => {
  const doc = new jsPDF();

  // --- 1. Add Header with Logo ---
  try {
    const logoUrl = '/press-pass.png';
    const img = new Image();
    img.crossOrigin = 'anonymous';

    await new Promise((resolve, reject) => {
      img.onload = resolve;
      img.onerror = reject;
      img.src = logoUrl;
    });

    doc.addImage(img, 'PNG', 20, 10, 30, 30);
    doc.setFontSize(20);
    doc.text('Balance Statement', 60, 30);
    doc.setFontSize(10);
    doc.text(`Generated on: ${new Date().toLocaleDateString('en-GB')}`, 60, 40);
  } catch (error) {
    console.warn('Could not load logo, generating PDF without it:', error);
    doc.setFontSize(20);
    doc.text('Balance Statement', 20, 30);
    doc.setFontSize(10);
    doc.text(`Generated on: ${new Date().toLocaleDateString('en-GB')}`, 20, 40);
  }

  let yPos = 60;

  // --- 2. Add Summary ---
  doc.setFontSize(14);
  doc.text('Summary', 20, yPos);
  yPos += 15;

  doc.setFontSize(12);
  doc.text(`Available Balance: R${wallet.availableBalance.toLocaleString()},00`, 20, yPos);
  doc.text(`Total Earnings: R${wallet.totalEarnings.toLocaleString()},00`, 20, yPos + 10);
  doc.text(`Total Withdrawn: R${wallet.withdrawn.toLocaleString()},00`, 20, yPos + 20);
  yPos += 40;

  // --- 3. Add Transaction History ---
  doc.setFontSize(14);
  doc.text('Transaction History', 20, yPos);
  yPos += 15;

  // Table Headers
  const tableHeaders = ['Date', 'Time', 'Source', 'Description', 'Amount', 'Status'];
  const colWidths = [30, 25, 30, 50, 20, 20];
  let xPos = 20;

  doc.setFontSize(10);
  tableHeaders.forEach((header, i) => {
    doc.text(header, xPos, yPos);
    xPos += colWidths[i];
  });
  doc.line(20, yPos + 2, 190, yPos + 2); // Underline headers
  yPos += 10;

  // Table Rows
  transactionsToExport.forEach((t) => {
    if (yPos > 270) { // Add new page if content overflows
      doc.addPage();
      yPos = 30;
    }

    const amount = t.type === 'earning' ? `+R${t.amount.toLocaleString()}` : `-R${t.amount.toLocaleString()}`;
    xPos = 20;

    doc.text(t.date || '', xPos, yPos);
    xPos += colWidths[0];
    doc.text(t.time || '', xPos, yPos);
    xPos += colWidths[1];
    doc.text((t.source || 'N/A').substring(0, 15), xPos, yPos);
    xPos += colWidths[2];
    doc.text((t.description || 'N/A').substring(0, 25), xPos, yPos);
    xPos += colWidths[3];
    doc.text(amount, xPos, yPos);
    xPos += colWidths[4];
    doc.text(t.status || '', xPos, yPos);

    yPos += 8;
  });

  // --- 4. Add Footer to all pages ---
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(`Page ${i} of ${pageCount}`, 180, 285);
    doc.text('Generated by PressPass Wallet System', 20, 285);
  }

  // --- 5. Save the PDF ---
  const fileName = `balance-statement-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};