"use client"

import { useState } from "react"
import Link from "next/link"
import { ArrowLeft, Check, Clock, X, Download } from "lucide-react"
import { useCurrentPublisher } from "@/hooks/useCurrentPublisher"
import { useWallet } from "@/hooks/useWallet"
import jsPDF from 'jspdf'

export default function BalanceStatement() {
  const { publisher, loading: publisherLoading } = useCurrentPublisher("currentPublisherId")
  const wallet = useWallet(publisher?.id)

  // Show loading state
  if (publisherLoading || wallet.loading) {
    return (
      <div className="bg-white border rounded-lg shadow-xl w-full max-w-4xl mx-auto p-6">
        <div className="flex items-center justify-center py-12">
          <div className="text-center">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
            <p className="mt-2 text-gray-600">Loading balance statement...</p>
          </div>
        </div>
      </div>
    )
  }

  // Show error state
  if (wallet.error) {
    return (
      <div className="bg-white border rounded-lg shadow-xl w-full max-w-4xl mx-auto p-6">
        <div className="flex items-center justify-center py-12">
          <div className="text-center text-red-600">
            <p>Error loading balance statement: {wallet.error}</p>
            <button
              onClick={() => window.location.reload()}
              className="mt-4 bg-blue-600 text-white px-4 py-2 rounded"
            >
              Retry
            </button>
          </div>
        </div>
      </div>
    )
  }

  // Check if publisher is loaded
  if (!publisher || !publisher.id) {
    return (
      <div className="bg-white border rounded-lg shadow-xl w-full max-w-4xl mx-auto p-6">
        <div className="flex items-center justify-center py-12">
          <div className="text-center text-orange-600">
            <p>Publisher data not available</p>
            <p className="text-sm text-gray-600 mt-2">Please make sure you're logged in</p>
          </div>
        </div>
      </div>
    )
  }

  // PDF Generation Function
  const generatePDF = () => {
    const doc = new jsPDF()

    // Add title
    doc.setFontSize(20)
    doc.text('Balance Statement', 20, 30)

    // Add generation date
    doc.setFontSize(10)
    doc.text(`Generated on: ${new Date().toLocaleDateString('en-GB')}`, 20, 40)

    // Add summary section
    doc.setFontSize(14)
    doc.text('Summary', 20, 60)

    doc.setFontSize(12)
    doc.text(`Available Balance: R${wallet.availableBalance.toLocaleString()},00`, 20, 75)
    doc.text(`Total Earnings: R${wallet.totalEarnings.toLocaleString()},00`, 20, 85)
    doc.text(`Total Withdrawn: R${wallet.withdrawn.toLocaleString()},00`, 20, 95)

    // Add transactions section
    doc.setFontSize(14)
    doc.text('Transaction History', 20, 115)

    // Table headers
    doc.setFontSize(10)
    doc.text('Date', 20, 130)
    doc.text('Time', 50, 130)
    doc.text('Source', 75, 130)
    doc.text('Description', 105, 130)
    doc.text('Amount', 155, 130)
    doc.text('Status', 175, 130)

    // Draw header line
    doc.line(20, 132, 190, 132)

    // Add transactions
    let yPosition = 140
    wallet.transactions.slice(0, 20).forEach((transaction, index) => {
      if (yPosition > 270) { // If near bottom of page, add new page
        doc.addPage()
        yPosition = 30
      }

      const amount = transaction.type === 'earning'
        ? `+R${transaction.amount.toLocaleString()}`
        : `-R${transaction.amount.toLocaleString()}`

      doc.text(transaction.date || '', 20, yPosition)
      doc.text(transaction.time || '', 50, yPosition)
      doc.text((transaction.source || 'N/A').substring(0, 15), 75, yPosition)
      doc.text((transaction.description || 'N/A').substring(0, 25), 105, yPosition)
      doc.text(amount, 155, yPosition)
      doc.text(transaction.status || '', 175, yPosition)

      yPosition += 8
    })

    // Add footer
    const pageCount = doc.internal.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.text(`Page ${i} of ${pageCount}`, 180, 285)
      doc.text('Generated by PressPass Wallet System', 20, 285)
    }

    // Save the PDF
    const fileName = `balance-statement-${new Date().toISOString().split('T')[0]}.pdf`
    doc.save(fileName)
  }

  return (
    <div className="bg-white border rounded-lg shadow-xl w-full max-w-4xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between p-6 border-b">
        <div className="flex items-center">
          <Link
            href="/print-media/wallet"
            className="flex items-center text-blue-600 hover:text-blue-800 mr-4"
          >
            <ArrowLeft size={20} />
          </Link>
          <h2 className="text-xl font-semibold text-gray-900">Balance Statement</h2>
        </div>
        <button className="text-gray-600 hover:text-black flex items-center gap-1 text-sm">
          Filter
        </button>
      </div>

      {/* Modal Content */}
      <div className="p-6">
        {/* Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <p className="text-sm font-medium text-blue-700">Available Balance</p>
            <p className="text-2xl font-bold text-blue-900">
              R{wallet.availableBalance.toLocaleString()},00
            </p>
          </div>
          <div className="bg-green-50 border border-green-200 rounded-lg p-4">
            <p className="text-sm font-medium text-green-700">Total Earnings</p>
            <p className="text-2xl font-bold text-green-900">
              R{wallet.totalEarnings.toLocaleString()},00
            </p>
          </div>
          <div className="bg-red-50 border border-red-200 rounded-lg p-4">
            <p className="text-sm font-medium text-red-700">Total Withdrawn</p>
            <p className="text-2xl font-bold text-red-900">
              R{wallet.withdrawn.toLocaleString()},00
            </p>
          </div>
        </div>

        {/* Transaction Table */}
        <div className="bg-white border border-gray-200 rounded-lg overflow-hidden">
          <div className="px-6 py-4 border-b border-gray-200">
            <h3 className="text-lg font-medium text-gray-900">Transaction History</h3>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left font-medium text-gray-700">Date</th>
                  <th className="px-6 py-3 text-left font-medium text-gray-700">Time</th>
                  <th className="px-6 py-3 text-left font-medium text-gray-700">Source</th>
                  <th className="px-6 py-3 text-left font-medium text-gray-700">Description</th>
                  <th className="px-6 py-3 text-left font-medium text-gray-700">Amount</th>
                  <th className="px-6 py-3 text-left font-medium text-gray-700">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {wallet.loading ? (
                  [...Array(5)].map((_, idx) => (
                    <tr key={idx} className="animate-pulse">
                      <td className="px-6 py-4"><div className="h-4 bg-gray-200 rounded w-16"></div></td>
                      <td className="px-6 py-4"><div className="h-4 bg-gray-200 rounded w-12"></div></td>
                      <td className="px-6 py-4"><div className="h-4 bg-gray-200 rounded w-20"></div></td>
                      <td className="px-6 py-4"><div className="h-4 bg-gray-200 rounded w-24"></div></td>
                      <td className="px-6 py-4"><div className="h-4 bg-gray-200 rounded w-16"></div></td>
                      <td className="px-6 py-4"><div className="h-4 bg-gray-200 rounded w-16"></div></td>
                    </tr>
                  ))
                ) : wallet.transactions.length > 0 ? (
                  wallet.transactions.map((transaction, idx) => (
                    <tr key={idx} className="hover:bg-gray-50">
                      <td className="px-6 py-4 text-gray-900">{transaction.date}</td>
                      <td className="px-6 py-4 text-gray-900">{transaction.time}</td>
                      <td className="px-6 py-4 text-gray-900">{transaction.source || 'N/A'}</td>
                      <td className="px-6 py-4 text-gray-900">{transaction.description || 'N/A'}</td>
                      <td className="px-6 py-4">
                        <span className={`font-medium ${
                          transaction.type === 'earning' ? 'text-green-600' : 'text-red-600'
                        }`}>
                          {transaction.type === 'earning' ? '+' : '-'}R{transaction.amount.toLocaleString()}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <span className={`inline-flex px-2 py-1 text-xs font-medium rounded-full ${
                          transaction.status === 'success'
                            ? 'bg-green-100 text-green-800'
                            : transaction.status === 'processing'
                            ? 'bg-yellow-100 text-yellow-800'
                            : 'bg-red-100 text-red-800'
                        }`}>
                          {transaction.status}
                        </span>
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan="6" className="px-6 py-8 text-center text-gray-500">
                      No transactions found
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>

        {/* Footer */}
        <div className="flex justify-between items-center mt-6">
          <div className="flex items-center gap-3">
            <Link
              href="/print-media/wallet/balance-statement"
              className="bg-blue-600 text-white rounded px-4 py-2 text-sm font-medium"
            >
              Balance Statement
            </Link>
            <Link
              href="/print-media/wallet/withdrawal-history"
              className="border rounded px-4 py-2 text-sm font-medium"
            >
              Withdrawal History
            </Link>
          </div>
          <div className="flex items-center gap-3">
            <Link
              href="/print-media/wallet"
              className="border rounded px-4 py-2 text-sm font-medium"
            >
              Back to Wallet
            </Link>
            <button
              onClick={generatePDF}
              className="bg-blue-600 text-white rounded px-4 py-2 text-sm font-medium hover:bg-blue-700 flex items-center gap-2"
            >
              <Download size={16} />
              Download Statement
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}